BACKUP = "Backup Files"
BACKUP_TOOLTIP = "Create a backup of the files before renaming."
CHANGE_EXT = "Change Extension:"
CHANGE_EXT_DEFAULT = "...ext"
CHANGE_EXT_TOOLTIP = "When checked the selected items extensions will be changed."
COLOR_DISABLED = "color: gray"
COLOR_INVALID = "color: #ab1128"
COLOR_VALID = "color:black"
COMPLETE_RENAME = "Complete Rename:"
COMPLETE_RENAME_DEFAULT = "...new name"
COMPLETE_RENAME_TOOLTIP = "When checked the selected items will be completely renamed."
OPTIONS = "OPTIONS"
PADDING = "Padding:"
PADDING_TOOLTIP = "Set the padding to apply to the renumbering."
PREVIEW = "preview"
PREVIEW_TOOLTIP = "When checked a preview of the renaming will show next to the original name."
PREFIX = "Add prefix:"
PREFIX_DEFAULT = "...prefix"
PREFIX_TOOLTIP = "When checked add a prefix to the files being renamed."
REMOVE_EXT = "Remove Extension"
REMOVE_EXT_TOOLTIP = "Remove the extension when renaming.\nThis is useful if you have an incorrect ext applied."
REPLACE_WITH_DEFAULT = "...replace with"
RENUMBER = "Renumber"
RENUMBER_TOOLTIP = ("When checked add renumbering to the selected items.\n"
                    "Drag and Drop the selected items in the order you want the renumbering to happen.")
SEARCH_AND_REPLACE = "Search / Replace:"
SEARCH_AND_REPLACE_DEFAULT = "...search for"
SEARCH_AND_REPLACE_TOOLTIP = "When Checked search for a string of text and replace with a new string."
START_NUM = "Starting Number:"
START_NUM_TOOLTIP = "Set the start number for the renaming utilize."
USE_DOT = "Use Dot Numbering"
USE_DOT_TOOLTIP = "Use a dot notation when numbering.\nExample: name.001.ext."

SPACER_SIZE = (25, 25)
DOT_WIDTH = 200
PADDING_MIN_WIDTH = 50
START_NUM_MIN_WIDTH = 50
START_NUM_DEFAULT = 1
REPLACE_WIDTH = 200
FIND_WIDTH = 200
NEW_NAME_WIDTH = 200
PREFIX_WIDTH = 200
MIN_PADDING = 1
MAX_PADDING = 9
